---
- name: install the bombjack server on a VPS on Ubuntu v20
  hosts: serveur_ovh
  become: yes
  remote_user: ubuntu
  vars:
    password: xxxxxxx
    # created with:
    # python -c "from passlib.hash import sha512_crypt; import getpass; print (sha512_crypt.encrypt(getpass.getpass()))"

  pre_tasks:
  - name: ensure server is up to date
    apt:
      update_cache: yes
      upgrade: full

  - name: install pip, gunicorn
    apt: 
      name: [python3-pip, gunicorn]

  - name: install python packages
    pip:
      name: [python-daemon, sdnotify, sqlalchemy, flask]
      state: latest

  - name: add local user
    user: name=laurent password={{password}} shell=/bin/bash groups="sudo"
  
  - name: copy the file of the highscores and pyhton files
    synchronize: 
      src: files/bombjack/ 
      dest: /home/laurent/bombjack
      delete: yes
      rsync_opts:
        - "--chmod=F644"
    notify:
      - restart gunicorn

  - name: copy the service file for gunicorn
    template:
      src=templates/gunicorn.service
      dest=/etc/systemd/system/gunicorn.service
    notify:
      - restart gunicorn

  post_tasks:
  - name: add database games
    become: true
    become_user: postgres
    community.postgresql.postgresql_db:
      name: games

  - name: add table highscores
    become: true
    become_user: postgres
    community.postgresql.postgresql_table:
      db: games
      name: highscores
      columns: 
      - id int generated by default as identity primary key
      - name varchar(3)
      - score int
      - round int

  - name: add table sessions
    become: true
    become_user: postgres
    community.postgresql.postgresql_table:
      db: games
      name: sessions
      columns: 
      - id varchar(32)
      - creation timestamp default current_timestamp
      - level_done int default 0
      - score int default 0

  - name: add the role/user laurent
    become: true
    become_user: postgres
    community.postgresql.postgresql_user:
      db: games
      name: laurent

  - name: grants for the user laurent
    become: true
    become_user: postgres
    community.postgresql.postgresql_privs:
      db: games
      role: laurent
      objs: ALL_IN_SCHEMA
      privs: SELECT,INSERT,UPDATE,DELETE

  - name: Check the presence of highscores
    become: true
    become_user: postgres
    community.postgresql.postgresql_query:
      db: games
      query: select count(*) from highscores
    register: query_scores

  - name: fill the table highscores (if empty) with csv file 
    become: true
    become_user: postgres
    when: query_scores.query_all_results[0][0]["count"] == 0
    community.postgresql.postgresql_copy:
      db: games
      copy_from: /home/laurent/bombjack/highscores.csv
      dst: highscores
      columns: score, name, round
      options:
        delimiter: ';'
        format: csv

  handlers:
    - name: restart gunicorn
      become: yes
      become_user: root
      systemd:
        name: gunicorn.service
        daemon-reload: yes
        enabled: yes
        state: restarted

  roles:
    - role: geerlingguy.postgresql
  


